### ISSUE TITLE
Preprocess of TREC dataset

### ISSUE THREAD

**Issue by zhi-xuan-chen** [night-chen/DyGen#1]
I noticed the split of the original trec dataset is different from that in your paper, so how to preprocess the raw dataset?

I found the trec dataset in here [trec](https://cogcomp.seas.upenn.edu/Data/QA/QC/)

**Comment by night-chen** [comment]
Hi Zhixuan,

You can find the data link here: https://github.com/JieyuZ2/wrench#classification, and the labeling functions in the attached image. Each of the labeling functions can be used to label one class, you can directly download the raw data and process it with the labeling rules we have provided. Thank you so much!
![lfs](https://github.com/night-chen/DyGen/assets/20238874/2e5d4e7f-47d8-43a8-8849-1a70f4a14bed)

Best,
Yuchen
